### PR TITLE
OrdinalScale formula had an overflow going past the range

### LINKED ISSUE #66: [BUG] bar clipped on the most right
**Describe the bug**

Image

**To Reproduce**

```
diff --git a/example/lib/graphs/bar_chart.dart b/example/lib/graphs/bar_chart.dart
index 162691e..034b123 100644
--- a/example/lib/graphs/bar_chart.dart
+++ b/example/lib/graphs/bar_chart.dart
@@ -21,7 +21,7 @@ Widget buildBarChartTab(ChartTheme currentTheme,
           height: 400,
           child: CristalyseChart()
               .data(data)
-              .mapping(x: 'quarter', y: 'revenue')
+              .mapping(x: 'quarter', y: 'revenue', color: 'bar')
               .geomBar(width: sliderValue.clamp(0.1, 1.0), alpha: 0.8)
               .scaleXOrdinal()
               .scaleYContinuous(min: 0)
diff --git a/example/lib/screens/chart_screen.dart b/example/lib/screens/chart_screen.dart
index 10d17dd..5db47aa 100644
--- a/example/lib/screens/chart_screen.dart
+++ b/example/lib/screens/chart_screen.dart
@@ -133,11 +133,33 @@ class _ChartScreenState extends State<ChartScreen>
     });
 
     // Realistic bar chart - Quarterly Revenue
-    final quarters = ['Q1 2024', 'Q2 2024', 'Q3 2024', 'Q4 2024'];
+    final quarters = [
+      'Q1 2024',
+      'Q2 2024',
+      'Q3 2024',
+      'Q4 2024',
+      'Q5 2024',
+      'Q6 2024',
+      'Q7 2024',
+      'Q8 2024',
+      'Q9 2024',
+      'Q10 2024',
+    ];
     _barChartData = quarters.asMap().entries.map((entry) {
       final revenue = 120 + entry.key * 25 + math.Random().nextDouble() * 20;
-      return {'quarter': entry.value, 'revenue': revenue};
+      return {
+        'quarter': entry.value,
+        'revenue': revenue,
+        'bar': 'Bar 1',
+      };
     }).toList();
+    _barChartData.addAll(quarters
+        .map((e) => {
+              'quarter': e,
+              'revenue': 120 + math.Random().nextDouble() * 20,
+              'bar': 'Bar 2'
+            })
+        .toList());
```

### PR DESCRIPTION
**Pull request by jbbjarnason**
Fixes https://github.com/rudi-q/cristalyse/issues/66

The fix was made by Claude

### CODE REVIEW

File: example/lib/screens/chart_screen.dart [hunk 1]
```diff
@@ -133,13 +133,37 @@ class _ChartScreenState extends State<ChartScreen>
     });
 
     // Realistic bar chart - Quarterly Revenue
-    final quarters = ['Q1 2024', 'Q2 2024', 'Q3 2024', 'Q4 2024'];
+    final quarters = [
```
Comment (rudi-q) [inline example/lib/screens/chart_screen.dart:136]: Are we changing from 'quarterly revenue' to 'monthly revenue', given that the values here represent months instead of quarters?

@jbbjarnason

Comment (jbbjarnason) [reply example/lib/screens/chart_screen.dart:136]: This was my bad. Great spot @rudi-q .

I changed to 3 years of quarterly data, to reproduce the previous bug.

Comment (rudi-q) [reply example/lib/screens/chart_screen.dart:136]: thanks for the revision! @jbbjarnason 
LGTM now!
